### PR TITLE
Start work on Docker vignette

### PR DESCRIPTION
**Pull request by maelle**
Not ready yet, and only to be merged after #221 (that will have added the vignettes infrastructure in DESCRIPTION etc.)

### CODE REVIEW

**Comment by maelle** [comment]
@gaborcsardi do you have any link about bash installation for Windows? Otherwise I'll just use the first one Google provides me with.

**Comment by gaborcsardi** [comment]
It is very unlikely that this script will work on Windows, even if bash is installed. We would need to test it on windows, but I don't have any Windows machines that could run Docker.

**Comment by maelle** [comment]
Is it unlikely because of bash? We could make a call for testers on Twitter :wink:

**Comment by gaborcsardi** [comment]
Not because of bash, bash is fine, that's bash, but because of the other tools used, which are available on Unix/Linux, but not on Windows, e.g. `tar`, etc.

**Comment by maelle** [comment]
:+1:

**Comment by gaborcsardi** [comment]
I'll buy a Windows laptop at some point, but for now we can just say that Windows is untested and it might work if you have the tools, and that reports about it are welcome.

**Comment by maelle** [comment]
@gaborcsardi this PR is ready for review but please review #221 first :-)

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by maelle** [comment]
Ok thanks so the very last section about starting containers is not totally wrong?

**Pull request merged**
