### PR TITLE
Support the new group-wise /list API

### PR DESCRIPTION
**Pull request by maelle**
This is incomplete.

### CODE REVIEW

**Comment by maelle** [comment]
Reg printing what seems logical to me would be to make the part of the `row.name` that corresponds to the group ID bold/a different color, but I'm not sure how to best achieve this.

**Comment by maelle** [comment]
I actually removed `row.names`. The printing output now has both `group` and `id`, would `group` be enough?

``` r

rhub::list_package_checks("/home/maelle/Documents/R-hub/test-packages/note",
                          email = "maelle.salmon@yahoo.se",
                          howmany = 4)
#>  package version status submitted             platform
#>     note     1.0   note   ~2h ago windows-x86_64-devel
#>     note     1.0   note   ~2h ago   ubuntu-gcc-release
#>     note     1.0   note   ~2h ago   fedora-clang-devel
#>     note     1.0     ok   ~4d ago     debian-gcc-devel
#>     note     1.0   note   ~6d ago   fedora-clang-devel
#>     note     1.0   note   ~6d ago windows-x86_64-devel
#>     note     1.0   note   ~6d ago   ubuntu-gcc-release
#>     note     1.0     ok  ~32d ago     debian-gcc-devel
#>                                             group
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>                                                  
#>  note_1.0.tar.gz-c4abbbe41c884a65a9e7dea0f166fe17
#>  note_1.0.tar.gz-c4abbbe41c884a65a9e7dea0f166fe17
#>  note_1.0.tar.gz-c4abbbe41c884a65a9e7dea0f166fe17
#>                                                  
#>                                                id
#>  note_1.0.tar.gz-4f9113c77256452791043ac07787ada8
#>  note_1.0.tar.gz-6761ed27a295401286be600994037c12
#>  note_1.0.tar.gz-f8bc9d2e812e42ba88dae2002c300d0b
#>  note_1.0.tar.gz-d3b8509d709e7ce30956ae764388887c
#>  note_1.0.tar.gz-0a9b7c77e7ca49b083d439483b658b44
#>  note_1.0.tar.gz-42cb5428d955424c83113fc40d303b58
#>  note_1.0.tar.gz-7cf1c5f8132c4195a03b0cb75d2f908a
#>  note_1.0.tar.gz-b254781102ee490e8272cac8b474f7d8
rhub::list_my_checks(howmany = 3)
#>  package version  status submitted             platform
#>     note     1.0    note   ~2h ago windows-x86_64-devel
#>     note     1.0    note   ~2h ago   ubuntu-gcc-release
#>     note     1.0    note   ~2h ago   fedora-clang-devel
#>  warning     1.0 warning   ~4d ago     debian-gcc-devel
#>     note     1.0      ok   ~4d ago     debian-gcc-devel
#>                                             group
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>                                                  
#>                                                  
#>                                                   id
#>     note_1.0.tar.gz-4f9113c77256452791043ac07787ada8
#>     note_1.0.tar.gz-6761ed27a295401286be600994037c12
#>     note_1.0.tar.gz-f8bc9d2e812e42ba88dae2002c300d0b
#>  warning_1.0.tar.gz-fd6bd706008cfa5a72795234d0f42450
#>     note_1.0.tar.gz-d3b8509d709e7ce30956ae764388887c
```

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note that `howmany` now refers to a number of check groups, not a number of checks, I updated the docs accordingly.

I think the `id` could be useful if there were a way to subset the list cf #202 i.e. I call `rhub::list_package_checks()`, see one that got a `WARNING`, and use that `id` to subset the list and look at the details/web log for that check only.

**Comment by maelle** [comment]
What I added to the work by @gaborcsardi = `summary()` and `print()` methods for `rhub_check_list` objects, and a way to extract a single/multiple check from the list. Example below.

``` r
lala <- rhub::list_package_checks("/home/maelle/Documents/R-hub/test-packages/note",
                          email = "maelle.salmon@yahoo.se",
                          howmany = 4)

lala$print()
#>  package version status submitted             platform
#>     note     1.0   note   ~2d ago windows-x86_64-devel
#>     note     1.0   note   ~2d ago   ubuntu-gcc-release
#>     note     1.0   note   ~2d ago   fedora-clang-devel
#>     note     1.0     ok   ~6d ago     debian-gcc-devel
#>     note     1.0   note   ~8d ago   fedora-clang-devel
#>     note     1.0   note   ~8d ago windows-x86_64-devel
#>     note     1.0   note   ~8d ago   ubuntu-gcc-release
#>     note     1.0     ok  ~34d ago     debian-gcc-devel
#>                                          group_id
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>  note_1.0.tar.gz-9ceef8e7031d4b9b97699004d86162ba
#>                                              <NA>
#>  note_1.0.tar.gz-c4abbbe41c884a65a9e7dea0f166fe17
#>  note_1.0.tar.gz-c4abbbe41c884a65a9e7dea0f166fe17
#>  note_1.0.tar.gz-c4abbbe41c884a65a9e7dea0f166fe17
#>                                              <NA>
#>                                          check_id
#>  note_1.0.tar.gz-4f9113c77256452791043ac07787ada8
#>  note_1.0.tar.gz-6761ed27a295401286be600994037c12
#>  note_1.0.tar.gz-f8bc9d2e812e42ba88dae2002c300d0b
#>  note_1.0.tar.gz-d3b8509d709e7ce30956ae764388887c
#>  note_1.0.tar.gz-0a9b7c77e7ca49b083d439483b658b44
#>  note_1.0.tar.gz-42cb5428d955424c83113fc40d303b58
#>  note_1.0.tar.gz-7cf1c5f8132c4195a03b0cb75d2f908a
#>  note_1.0.tar.gz-b254781102ee490e8272cac8b474f7d8

group_id <- lala$summary()$group_id[1]
group_check <- lala$get_group(group_id)
class(group_check)
#> [1] "rhub_check" "R6"

check_id <- lala$summary()$check_id[4]
single_check <- lala$get_check(check_id)
class(single_check)
#> [1] "rhub_check" "R6"
single_check
#> Updating status...
#> 
#> ── note 1.0: OK
#> 
#>   Build ID:   note_1.0.tar.gz-d3b8509d709e7ce30956ae764388887c
#>   Platform:   Debian Linux, R-devel, GCC
#>   Submitted:  6d 22h 41m 10.8s ago
#>   Build time: 45.5s
#> 
#> 0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

<sup>Created on 2019-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
