### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by maelle**
cf #151 

- Don't merge yet, I first need to solve the README "problem" (probably via a PR to `pkgdown`)

- the pkgdown website will need a change of gh-pages settings.

### CODE REVIEW

**Comment by maelle** [comment]
All set now :-)

**Comment by maelle** [comment]
Good point, done, but I think I might have found a "bug" in `roxygen2`: in check_for_cran as only "other shortcuts" it shows me `check_on_linux` and for other functions such as `check_on_linux` it shows me`check_for_cran` as many times as there are shortcuts:

image

Am going to remove the family tags to prevent that.

**Comment by maelle** [comment]
Mmh I can't solve this easily, it has something to do with family tag + having several functions documented in one file. 🤔 will think about it. You could merge, but the see also part is ugly.

**Comment by gaborcsardi** [comment]
Strange, I  though I had fixed this in roxygen years  ago. (https://github.com/klutometis/roxygen/pull/367) But seems like this is sg else. Can you remove the  family tags, please?

**Comment by maelle** [comment]
Yep will remove them.

I think the problem is somewhere in https://github.com/klutometis/roxygen/blob/be3ef309381923e64337c3324510746990fde62f/R/rd-family.R (the way the words are chosen for the See also stuff)

**Comment by maelle** [comment]
family tags removed, pkgdown reference config written by copy-pasting from the NAMESPACE 🙈

**Comment by gaborcsardi** [comment]
I forgot about the pkgdown reference.... never mind, it is good for now. :)

**Comment by gaborcsardi** [comment]
Thanks much!

**Pull request merged**
