### PR TITLE
Create lock.yml

### PR DESCRIPTION
**Pull request by maelle**
Should the app also be installed for other R-hub repos? All of them?

### CODE REVIEW

**Comment by maelle** [comment]
If we install the app for all repos, I wonder whether a default .github/lock.yml file can be created https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#creating-a-repository-for-default-files

**Comment by maelle** [comment]
Right but what about putting lock.yml in github.com/r-hub/.github instead? (to enable it for all repos at once)

Otherwise, if you prefer to have one lock.yml for some repos, yes I'll Rbuildignore it.

**Comment by gaborcsardi** [comment]
> Right but what about putting lock.yml in github.com/r-hub/.github instead? (to enable it for all repos at once)

Is that possible? If yes, then it is good.

**Comment by maelle** [comment]
I'll try that!

**Pull request closed without merging**
