### PR TITLE
docs: Update README

### PR DESCRIPTION
**Pull request by krlmlr**
How would I render the README with minimal changes? My goal was to include the new-ish rchk runner.

Also, should the `rhub_platforms()` function have an example that is run in pkgdown mode only (`Sys.getenv("IN_PKGDOWN")`)?

Is asciicast actually used for animated images here, or only for coloring the output in the pkgdown? For the latter case, I'm now using a separate `index.md` that is created as a side effect of rendering `README.Rmd`, see, e.g., https://github.com/tidyverse/duckplyr/blob/main/README.Rmd#L21-L33.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
> How would I render the README with minimal changes?

```
rmarkdown::render("README.Rmd")
```
and then undo the changes you don't like. You probably don't need to change the SVG files.

**Comment by gaborcsardi** [comment]
I updated the README, it needs to run with dev asciicast to create the images.

**Comment by gaborcsardi** [comment]
I guess that also added rchk, so we can close this PR?

**Comment by krlmlr** [comment]
Thanks, all well now!

**Pull request closed without merging**
