### PR TITLE
Rename vignette to appear as 'Get Started'

### PR DESCRIPTION
**Pull request by Rekyt**
Hi,
According to [`pkgdown` documentation](https://pkgdown.r-lib.org/articles/pkgdown.html#navigation-bar) in default configuration a vignette named the same as the package can directly appear as `Get Started` in the navbar so it is more accessible.
So I propose to rename the `Get Started` vignette to benefit from these default options.

### CODE REVIEW

**Comment by maelle** [comment]
Thank you!

**Comment by maelle** [comment]
@Rekyt any idea why the vignette no longer appears in the "articles" drop-down menu?

**Comment by maelle** [comment]
ooops because it has its own tab which was the goal... sorry!!

**Comment by Rekyt** [comment]
Sorry maybe I wasn't explicit enough in the first PR message :stuck_out_tongue:

**Pull request merged**
