### PR TITLE
After check_for_cran print summary of systems

### PR DESCRIPTION
**Pull request by maelle**
To address #77 

There's probably a lot of things missing from this implementation but here's what I can get.

``` r
mychecks <- rhub::list_my_checks(howmany = 3)
mychecks$print_system()
#>   -  Fedora Linux, R-devel, clang, gfortran 
#>   -  Ubuntu Linux 16.04 LTS, R-release, GCC 
#>   -  Windows Server 2008 R2 SP1, R-devel, 32/64 bit
```

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Oh, I think the OP meant that if you do a `check_for_cran()` or anything else that  has  multiple platforms, after  they are done, you would print the  summary of all the results.

**Comment by maelle** [comment]
Indeed, any reason for it not to return a list?

**Comment by maelle** [comment]
Probably very naive but in `check()`

could `chk <- rhub_check$new(ids = vapply(response, "[[", "", "id"))` have a condition on the length of `vapply(response, "[[", "", "id")` and create a `rhub_check_list` when there is more than one id?

**Comment by maelle** [comment]
And was `rhub_check_for_cran` a placeholder?

**Comment by gaborcsardi** [comment]
> Indeed, any reason for it not to return a list?

Multiple platforms were not supported originally.

>  when there is more than one id?

That's an anti-pattern in general, i.e. returning different data types depending on the input. I think it should always returns a list.

> And was rhub_check_for_cran a placeholder?

I am not sure what you mean.

**Comment by maelle** [comment]
ok, so what about my trying to experiment around a summary for list (and making check output a list)?

My question about `rhub_check_for_cran` is because the class seems to exist but doesn't seem used at all?

**Comment by gaborcsardi** [comment]
The list already has a print method:
```r
❯ mychecks
  package   version status submitted               platform
1     XML 3.98-1.16  error   ~1h ago windows-x86_64-release
2     XML 3.98-1.16  error   ~1h ago windows-x86_64-release
3  igraph     1.2.3  error   ~1h ago windows-x86_64-release
```

We can have a `report()` method to print markdown?

> doesn't seem used at all?

Oh, IDK, should be removed then, I guess.

**Comment by gaborcsardi** [comment]
Right. I would still call it `report()`, and it could me markdown-like.

**Comment by maelle** [comment]
Ok, good name.

The output should be:

* The list of platforms

* The results, what about
0 NOTE | 1 WARNING | 1 ERROR (count based on unique messages)
then a list of messages e.g.
```
- WARNING (platform1, platform2) message
- ERROR (platform1) message

```
so that the report also shows where each error/warning was observed?

**Comment by gaborcsardi** [comment]
Yeah, look at the `details()` method.

screen shot 2019-01-30 at 2 42 06 pm

**Comment by maelle** [comment]
Yes, I''ve copy-pasted it and am using it :grin:

**Comment by maelle** [comment]
This method should error if on tries to apply it to a list with
* more than one package and version
* more than one occurrence per platform, right?

Should it actually exist only for CRAN checks in which case `rhub_check_for_cran` would actually gain a role?

**Comment by gaborcsardi** [comment]
> Should it actually exist only for CRAN checks in which case rhub_check_for_cran would actually gain a role?

makes sense, but up to you

**Pull request closed without merging**
